import type { PublicDataBundle } from "@/types/datahub";
import { buildCanonicalName, normalizeCompanyName } from "@/lib/datahub/normalizers";

const generatedAt = "2026-07-15T09:30:00+09:00";

export const demoBundle: PublicDataBundle = {
  generatedAt,
  demo: true,
  products: [
    {
      id: "prd-ufo-150",
      canonicalName: buildCanonicalName("LED 공장등 UFO-AM6-150W 5700K"),
      displayName: "LED 공장등 UFO-AM6-150W 5700K",
      modelName: "UFO-AM6-150W",
      brand: "YNK",
      manufacturerId: "cmp-ynk",
      supplierIds: ["cmp-ynk", "cmp-cpntech"],
      marketTypes: ["procurement", "consumer"],
      category: "공장등",
      subcategory: "UFO 하이베이",
      specifications: {
        wattage: 150,
        luminousFlux: 21000,
        efficacy: 140,
        colorTemperature: 5700,
        cri: 80,
        powerFactor: 0.95,
        inputVoltage: "AC220V",
        beamAngle: 90,
        ipRating: "IP65",
        dimensions: "320x320x180",
        weight: "3.8kg",
        material: "알루미늄",
        installationType: "천장형",
        hsCode: "9405110000",
        countryOfOrigin: "대한민국",
      },
      certifications: [
        {
          type: "고효율기자재",
          number: "HE-2026-00111",
          issuer: "한국에너지공단",
          status: "유효",
          issuedAt: "2026-01-10",
        },
        {
          type: "KC",
          number: "SU11329-22001",
          issuer: "국가기술표준원",
          status: "유효",
          issuedAt: "2025-12-18",
        },
      ],
      images: ["/hero-main.png"],
      sourceRecords: [
        {
          sourceName: "조달청 상품정보",
          sourceType: "procurement",
          originalId: "G2B-LED-150-001",
          originalUrl: "https://example.com/procurement/ufo-am6-150",
          collectedAt: generatedAt,
          updatedAt: generatedAt,
          fetchStatus: "success",
          rawHash: "demo-proc-001",
        },
        {
          sourceName: "네이버 쇼핑",
          sourceType: "consumer",
          originalId: "NV-LED-150-001",
          originalUrl: "https://example.com/consumer/ufo-am6-150",
          collectedAt: generatedAt,
          updatedAt: generatedAt,
          fetchStatus: "success",
          rawHash: "demo-consumer-001",
        },
      ],
      firstSeenAt: "2026-05-12T09:00:00+09:00",
      lastSeenAt: generatedAt,
      status: "active",
      dataQualityScore: 94,
      demo: true,
    },
    {
      id: "prd-panel-50",
      canonicalName: buildCanonicalName("LED 평판등 PL-50W 6500K"),
      displayName: "LED 평판등 PL-50W 6500K",
      modelName: "PL-50W",
      brand: "루미스",
      manufacturerId: "cmp-lumis",
      supplierIds: ["cmp-lumis"],
      marketTypes: ["consumer"],
      category: "실내조명",
      subcategory: "평판등",
      specifications: {
        wattage: 50,
        luminousFlux: 5500,
        efficacy: 110,
        colorTemperature: 6500,
        cri: 80,
        inputVoltage: "AC220V",
        dimensions: "1285x320",
        installationType: "매입형",
      },
      certifications: [],
      images: ["/panel-interior.png"],
      sourceRecords: [
        {
          sourceName: "네이버 쇼핑",
          sourceType: "consumer",
          originalId: "NV-LED-050-002",
          originalUrl: "https://example.com/consumer/pl-50w",
          collectedAt: generatedAt,
          updatedAt: generatedAt,
          fetchStatus: "success",
          rawHash: "demo-consumer-002",
        },
      ],
      firstSeenAt: "2026-06-20T11:00:00+09:00",
      lastSeenAt: generatedAt,
      status: "active",
      dataQualityScore: 76,
      demo: true,
    },
    {
      id: "prd-flood-100",
      canonicalName: buildCanonicalName("LED 투광등 FL-100W 5700K"),
      displayName: "LED 투광등 FL-100W 5700K",
      modelName: "FL-100W",
      brand: "씨피엔텍",
      manufacturerId: "cmp-cpntech",
      supplierIds: ["cmp-cpntech"],
      marketTypes: ["procurement"],
      category: "투광등",
      subcategory: "옥외조명",
      specifications: {
        wattage: 100,
        efficacy: 115,
        colorTemperature: 5700,
        inputVoltage: "AC220V",
        ipRating: "IP66",
        installationType: "브라켓형",
      },
      certifications: [
        {
          type: "사회적가치실현기업",
          number: "R24SL00001125",
          status: "유효",
        },
      ],
      images: ["/solar-light.png"],
      sourceRecords: [
        {
          sourceName: "조달청 상품정보",
          sourceType: "procurement",
          originalId: "222231102_1060000001",
          originalUrl: "https://example.com/procurement/fl-100w",
          collectedAt: generatedAt,
          updatedAt: generatedAt,
          fetchStatus: "success",
          rawHash: "demo-proc-002",
        },
      ],
      firstSeenAt: "2026-07-01T09:00:00+09:00",
      lastSeenAt: generatedAt,
      status: "active",
      dataQualityScore: 84,
      demo: true,
    },
    {
      id: "prd-street-120",
      canonicalName: buildCanonicalName("LED 가로등 SL-120W 5000K"),
      displayName: "LED 가로등 SL-120W 5000K",
      modelName: "SL-120W",
      brand: "에코루멘",
      manufacturerId: "cmp-ecolumen",
      supplierIds: ["cmp-ecolumen"],
      marketTypes: ["procurement", "consumer"],
      category: "가로등",
      subcategory: "도로조명",
      specifications: {
        wattage: 120,
        luminousFlux: 16800,
        efficacy: 140,
        colorTemperature: 5000,
        ipRating: "IP66",
        inputVoltage: "AC220V",
      },
      certifications: [
        {
          type: "고효율기자재",
          number: "HE-2026-00088",
          status: "유효",
        },
      ],
      images: ["/strip-glow.png"],
      sourceRecords: [
        {
          sourceName: "조달청 상품정보",
          sourceType: "procurement",
          originalId: "G2B-STREET-120-009",
          originalUrl: "https://example.com/procurement/sl-120w",
          collectedAt: generatedAt,
          updatedAt: generatedAt,
          fetchStatus: "success",
          rawHash: "demo-proc-009",
        },
        {
          sourceName: "관리자 CSV 업로드",
          sourceType: "manual",
          originalId: "CSV-20260714-03",
          originalUrl: null,
          collectedAt: generatedAt,
          updatedAt: generatedAt,
          fetchStatus: "success",
          rawHash: "demo-manual-003",
        },
      ],
      firstSeenAt: "2026-07-10T10:00:00+09:00",
      lastSeenAt: generatedAt,
      status: "review",
      dataQualityScore: 88,
      demo: true,
    },
  ],
  companies: [
    {
      id: "cmp-ynk",
      name: "주식회사 와이앤케이",
      normalizedName: normalizeCompanyName("주식회사 와이앤케이"),
      businessNumber: "123-45-67890",
      companyType: "manufacturer",
      address: "경기도 김포시 구래동 123-4",
      region: "경기도 김포시",
      website: "https://example.com/ynk",
      productCount: 1,
      procurementProductCount: 1,
      consumerProductCount: 1,
      firstSeenAt: "2026-05-12T09:00:00+09:00",
      lastSeenAt: generatedAt,
      demo: true,
    },
    {
      id: "cmp-cpntech",
      name: "주식회사 씨피엔텍",
      normalizedName: normalizeCompanyName("주식회사 씨피엔텍"),
      businessNumber: "131-86-10636",
      companyType: "mixed",
      address: "인천광역시 남동구 남동동로 84",
      region: "인천광역시 남동구",
      website: "https://example.com/cpntech",
      productCount: 2,
      procurementProductCount: 2,
      consumerProductCount: 1,
      firstSeenAt: "2026-07-01T09:00:00+09:00",
      lastSeenAt: generatedAt,
      demo: true,
    },
    {
      id: "cmp-lumis",
      name: "루미스",
      normalizedName: normalizeCompanyName("루미스"),
      businessNumber: "214-81-30001",
      companyType: "seller",
      address: "서울특별시 금천구 가산동 88-1",
      region: "서울특별시 금천구",
      website: "https://example.com/lumis",
      productCount: 1,
      procurementProductCount: 0,
      consumerProductCount: 1,
      firstSeenAt: "2026-06-20T11:00:00+09:00",
      lastSeenAt: generatedAt,
      demo: true,
    },
    {
      id: "cmp-ecolumen",
      name: "에코루멘",
      normalizedName: normalizeCompanyName("에코루멘"),
      businessNumber: "110-23-99887",
      companyType: "mixed",
      address: "부산광역시 강서구 대저2동 41-3",
      region: "부산광역시 강서구",
      website: "https://example.com/ecolumen",
      productCount: 1,
      procurementProductCount: 1,
      consumerProductCount: 1,
      firstSeenAt: "2026-07-10T10:00:00+09:00",
      lastSeenAt: generatedAt,
      demo: true,
    },
  ],
  listings: [
    {
      id: "lst-ufo-1",
      productId: "prd-ufo-150",
      source: "Naver Shopping",
      sourceProductId: "nv-10001",
      sellerName: "YNK 공식몰",
      title: "LED 공장등 UFO-AM6-150W 5700K",
      price: 118000,
      shippingFee: 0,
      totalPrice: 118000,
      rating: 4.8,
      reviewCount: 31,
      productUrl: "https://example.com/store/ufo-am6-150w",
      imageUrl: "/hero-main.png",
      availability: "available",
      collectedAt: generatedAt,
      marketType: "consumer",
      demo: true,
    },
    {
      id: "lst-ufo-2",
      productId: "prd-ufo-150",
      source: "CSV Upload",
      sourceProductId: "csv-ynk-001",
      sellerName: "산업조명몰",
      title: "UFO 하이베이 150W 5700K",
      price: 121000,
      shippingFee: 3000,
      totalPrice: 124000,
      rating: 4.5,
      reviewCount: 12,
      productUrl: "https://example.com/store/ufo-highbay-150",
      imageUrl: "/hero-main.png",
      availability: "available",
      collectedAt: generatedAt,
      marketType: "consumer",
      demo: true,
    },
    {
      id: "lst-panel-1",
      productId: "prd-panel-50",
      source: "Naver Shopping",
      sourceProductId: "nv-10002",
      sellerName: "루미스몰",
      title: "LED 평판등 PL-50W 6500K",
      price: 42000,
      shippingFee: 3000,
      totalPrice: 45000,
      rating: 4.7,
      reviewCount: 48,
      productUrl: "https://example.com/store/pl-50w",
      imageUrl: "/panel-interior.png",
      availability: "available",
      collectedAt: generatedAt,
      marketType: "consumer",
      demo: true,
    },
    {
      id: "lst-street-1",
      productId: "prd-street-120",
      source: "CSV Upload",
      sourceProductId: "csv-eco-007",
      sellerName: "에코루멘 온라인",
      title: "LED 가로등 SL-120W 5000K",
      price: 268000,
      shippingFee: 0,
      totalPrice: 268000,
      rating: 4.6,
      reviewCount: 9,
      productUrl: "https://example.com/store/sl-120w",
      imageUrl: "/strip-glow.png",
      availability: "available",
      collectedAt: generatedAt,
      marketType: "consumer",
      demo: true,
    },
  ],
  priceHistory: [
    {
      id: "ps-ufo-1",
      productId: "prd-ufo-150",
      listingId: "lst-ufo-1",
      price: 120000,
      shippingFee: 0,
      totalPrice: 120000,
      collectedAt: "2026-07-11T09:00:00+09:00",
      demo: true,
    },
    {
      id: "ps-ufo-2",
      productId: "prd-ufo-150",
      listingId: "lst-ufo-1",
      price: 118000,
      shippingFee: 0,
      totalPrice: 118000,
      collectedAt: generatedAt,
      demo: true,
    },
    {
      id: "ps-panel-1",
      productId: "prd-panel-50",
      listingId: "lst-panel-1",
      price: 47000,
      shippingFee: 3000,
      totalPrice: 50000,
      collectedAt: "2026-07-11T09:00:00+09:00",
      demo: true,
    },
    {
      id: "ps-panel-2",
      productId: "prd-panel-50",
      listingId: "lst-panel-1",
      price: 42000,
      shippingFee: 3000,
      totalPrice: 45000,
      collectedAt: generatedAt,
      demo: true,
    },
    {
      id: "ps-street-1",
      productId: "prd-street-120",
      listingId: "lst-street-1",
      price: 257000,
      shippingFee: 0,
      totalPrice: 257000,
      collectedAt: "2026-07-11T09:00:00+09:00",
      demo: true,
    },
    {
      id: "ps-street-2",
      productId: "prd-street-120",
      listingId: "lst-street-1",
      price: 268000,
      shippingFee: 0,
      totalPrice: 268000,
      collectedAt: generatedAt,
      demo: true,
    },
  ],
  procurementRecords: [
    {
      id: "proc-ufo-1",
      productId: "prd-ufo-150",
      contractType: "다수공급자계약",
      registeredPrice: 132000,
      contractPrice: 129000,
      quantity: 60,
      amount: 7740000,
      buyer: "경기도교육청",
      supplier: "주식회사 와이앤케이",
      contractDate: "2026-07-08",
      sourceUrl: "https://example.com/procurement/ufo-am6-150",
      demo: true,
    },
    {
      id: "proc-flood-1",
      productId: "prd-flood-100",
      contractType: "다수공급자계약",
      registeredPrice: 150000,
      contractPrice: 150000,
      quantity: 50,
      amount: 7500000,
      buyer: "인천광역시청",
      supplier: "주식회사 씨피엔텍",
      contractDate: "2026-07-09",
      sourceUrl: "https://example.com/procurement/fl-100w",
      demo: true,
    },
    {
      id: "proc-street-1",
      productId: "prd-street-120",
      contractType: "조달우수제품",
      registeredPrice: 289000,
      contractPrice: 284000,
      quantity: 32,
      amount: 9088000,
      buyer: "부산광역시 강서구청",
      supplier: "에코루멘",
      contractDate: "2026-07-12",
      sourceUrl: "https://example.com/procurement/sl-120w",
      demo: true,
    },
  ],
  collectionRuns: [
    {
      runId: "run-proc-20260715",
      startedAt: "2026-07-15T08:50:00+09:00",
      finishedAt: generatedAt,
      sourceName: "ProcurementAdapter",
      success: true,
      fetchedCount: 124,
      insertedCount: 3,
      changedCount: 4,
      errorCount: 0,
      errorSummary: null,
      demo: true,
    },
    {
      runId: "run-naver-20260715",
      startedAt: "2026-07-15T08:55:00+09:00",
      finishedAt: generatedAt,
      sourceName: "NaverShoppingAdapter",
      success: true,
      fetchedCount: 212,
      insertedCount: 1,
      changedCount: 6,
      errorCount: 1,
      errorSummary: "일부 상품 리뷰 수 누락",
      demo: true,
    },
    {
      runId: "run-analytics-20260715",
      startedAt: "2026-07-15T09:00:00+09:00",
      finishedAt: generatedAt,
      sourceName: "AnalyticsEngine",
      success: true,
      fetchedCount: 4,
      insertedCount: 0,
      changedCount: 4,
      errorCount: 0,
      errorSummary: null,
      demo: true,
    },
  ],
  dataIssues: [
    {
      issueId: "issue-panel-missing-cert",
      productId: "prd-panel-50",
      issueType: "인증정보 누락",
      severity: "medium",
      description: "민수 데이터만 존재하여 인증번호 확인이 필요합니다.",
      sourceName: "NaverShoppingAdapter",
      detectedAt: generatedAt,
      resolved: false,
      demo: true,
    },
    {
      issueId: "issue-street-review",
      productId: "prd-street-120",
      issueType: "가격 급등 검토",
      severity: "high",
      description: "직전 수집 대비 총액이 4% 이상 상승했습니다.",
      sourceName: "AnalyticsEngine",
      detectedAt: generatedAt,
      resolved: false,
      demo: true,
    },
  ],
  analysisReports: [
    {
      id: "analysis-20260715-01",
      createdAt: generatedAt,
      title: "최근 7일 LED 조명 가격 변화",
      periodLabel: "최근 7일",
      dataPoints: 4,
      confidenceLabel: "예시 데이터",
      summary: "공장등 150W와 평판등 50W의 민수시장 총액이 하락했고, 가로등 120W는 상승했습니다.",
      details: [
        "UFO-AM6-150W 민수 총액은 직전 수집 대비 1.7% 하락했습니다.",
        "PL-50W 민수 총액은 직전 수집 대비 10.0% 하락했습니다.",
        "SL-120W 민수 총액은 직전 수집 대비 4.3% 상승했습니다.",
      ],
      demo: true,
    },
  ],
};
